### PR TITLE
added the first route which is insertig a new task to to the database…

### PR DESCRIPTION
**Pull request by majid76**
Hi Ahmed, I have done the first route, however, it needs lots of validation.
I have used the same branch that I have used for setting the database. What is your recommendation? should I delete the previous branch - databasesetup - and create a new one for app setup.
Thanks my awesome mentor

### CODE REVIEW

**Comment by AhmedShab** [comment]
Hey @majid76, Sorry I didn't check until now. Please add me to be the reviewer next time so I get a notification or mention me here 😄. 

I would normally delete the branches after accepting the PR. Then create a new branch for the new task. That's what developers usually do so it's good to get into this habit 👍.

Don't worry about this PR. After we merge it, the next task can be another branch.

**Comment by majid76** [comment]
HI Ahmed, It came to my mind after I have done my code.
For next stage, I will follow the habit.

**Comment by majid76** [comment]
Also, I will add you to be the reviewer from now onwards.

**Comment by AhmedShab** [comment]
@majid76 Btw, I'm trying to test it on my local machine but I'm getting few errors. Could you tell me how it's currently working, please (the connection to the database via knex)?

**Comment by AhmedShab** [comment]
Have a look at this article. It's pretty good and tells you more about how to wire the database with knex and express.
http://mherman.org/blog/2016/04/28/test-driven-development-with-node/#.WhCmiEqWZPY

**Comment by majid76** [comment]
@AhmedShab do you have mssql database installed on your machine?

**Comment by majid76** [comment]
@AhmedShab  very good link, however, I can see lot of developers follow the traditional way of creating and querying a database.
But, I am keen to try this module as I already know a bit of the traditional way and would like to use the new modules.
Thanks a lot, Mr.Mentor

**Comment by AhmedShab** [comment]
All good :). I have mssql installed but I'm not very familiar with it. I'll try and give it another go

**Comment by majid76** [comment]
Great :)

**Comment by majid76** [comment]
@AhmedShab I have done bad thing, I have deleted the branch before you merge the change. my app.js is clear/clean and empty now. hahahahahahahahaha

**Comment by AhmedShab** [comment]
@majid76, could you jump on the Stack channel? I need to ask you about mssql.

The branch is still on Github 🤔. We can discuss this online

**Pull request closed without merging**
